### PR TITLE
added `autoHideReferences` option to also close References search

### PR DESCRIPTION
**Pull request by ivribalko**
added `autoHideReferences` to also close References search i.e. [this panel](https://code.visualstudio.com/docs/editor/editingevolved#_peek).

### CODE REVIEW

**Comment by ivribalko** [comment]
@sirmspencer thank you for the great extension! please consider reviewing the suggested changes ⬆️ - it's something that i would love to have in `vscode-autohide` and maybe you'll also find it useful 🙏

**Comment by sirmspencer** [comment]
I probably wont add it myself, but feel free to push a PR.

**Comment by ivribalko** [comment]
> I probably wont add it myself, but feel free to push a PR.

@sirmspencer this is a PR, would you like me to open a different one?

**Comment by sirmspencer** [comment]
Ha, I looked too fast.  Looks good to me.

**Comment by sirmspencer** [comment]
I've reformatting my computer since the last release.  It might take me a second to get that set back up.

**Comment by ivribalko** [comment]
@sirmspencer any chance this might get released soon?

**Pull request merged**
