### PR TITLE
New features

### PR DESCRIPTION
**Pull request by nicolasmol**
**TOGGLE ICONS & HOTKEYS**

3 icons in the status bar for Sidebar, Panel and Auxiliary Bar.
Linked to 3 Hotkeys (in same order): 
- ctrl+esc, 
- ctrl+[Backquote] (on my keyword's layout it's the key below 'esc'), 
- alt+esc.
 
Peek 16-08-2023 22-35

Clicking an icon or press (event) the matching hotkey will do the same:

- **First event :** stand the chosen panel by (the icon becomes orange +  🕝️ ), meaning the panel is "unpinned" and will close once the user clicks in the editor.
- **Second event :** "pin" the panel (the icon becomes green + 📌 icon), meaning the panel will not close once the user clicks in the editor.
- **Third event :** deactivate the auto hiding for the panel.

**REVEAL PANEL ON ACTIVE DEBUG SESSION WHEN THE MOUSE LEAVES THE VSCODE'S WINDOW**
It reveals the Panel when the mouse leaves the VSCode window during a debug session. This is useful when the Panel is hidden and the user wants to see the debug output (can be turned on/off, + configurable delay)

_NOTES :_

_1. The package.json, has be modified to handle all those changes, in addition with small fixes, renaming logic & additional settings (e.g delay for AuxiliaryBar separated from Sidebar's one).
2. Unfortunately there is absolutely no way to catch the different user's "close panel"'s events, so that it's not possible to alter the icons consequently if the user closes intentionally a panel with the mouse_

### CODE REVIEW

**Comment by nicolasmol** [comment]
Improvement could be done in setting to alternate icons for ppl who have sidebar on right, auxiliary on left etc...

**Comment by sirmspencer** [comment]
Keybindings can and should mostly be handled outside of the extension itself.

**Comment by sirmspencer** [comment]
The rest looks like a solid improvement.  It'll take me a second to test it.

**Comment by sirmspencer** [comment]
Let's maybe split this up.  Adding the commands is an easy review I can go ahead and merge in.

**Comment by nicolasmol** [comment]
> Keybindings can and should mostly be handled outside of the extension itself.

For sure, we should. and as I suggested also being able to set panels positions with a a selector:
Sidebar/Panel/Auxiliary as:

- left/center/right
- right/center/left
- center/right/left
- right/left/center/

Tell me if you want I do it or yourself

**Comment by sirmspencer** [comment]
You are adding functionality that already exists.  I don't think we need to duplicate it here.
image

**Comment by nicolasmol** [comment]
> You are adding functionality that already exists. I don't think we need to duplicate it here. image

You're right.
I think I made changes accordingly

**Pull request closed without merging**
