### PR TITLE
Do not hide bottom panel on output clicking

### LINKED ISSUE #19: clicking in Output Window hides it
Clicking into the output window hides it.
Is it an issue with the extension or an individual setup problem?

### PR DESCRIPTION
**Pull request by sr-tream**
This resolves #19

### CODE REVIEW

**Review by artginzburg — APPROVED** [review]

**Review by rsvargas — APPROVED** [review]
Tested these changes and they work correctly

**Comment by sirmspencer** [comment]
I hear you. I need to get my box set up to publish, but I'll do it within the week.

**Comment by sirmspencer** [comment]
First step is to merge

**Comment by sirmspencer** [comment]
Can you please give me a change log statement

**Pull request merged**
