### PR TITLE
fix #8 define extension kind

### LINKED ISSUE #8: VSCode Remote compatibility
When using the Remote WSL extension this one is disabled on the host side and it is suggested to install it in WSL.
Is that intentional or doesn't this extension properly identify itself as a UI-only extension?
https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location

### PR DESCRIPTION
**Pull request by Trass3r**

### CODE REVIEW

**Comment by sirmspencer** [comment]
Do not make changes to package-lock.json.  That file should be in .gitignore anyway.

**Comment by Trass3r** [comment]
https://stackoverflow.com/a/44210813/594456

**Comment by sirmspencer** [comment]
There are more than one way to do things.  I update the repo to remove package-lock.json and add it to gitignore.

**Comment by sirmspencer** [comment]
The problem is that I cant pull your branch to make the change myself.

**Comment by Trass3r** [comment]
Forgot about this. Will look tomorrow.
But why wouldn't you be able to pull it, it's a public repo.

**Comment by sirmspencer** [comment]
Nevermind. Ill just copy the changes.  I need to add a change log entry and bump the version anyway.

**Comment by sirmspencer** [comment]
This will be in 1.0.7

**Pull request closed without merging**
